### ISSUE TITLE
설치 가이드 중 경로 문의(WM_LABEL_SIZE)

### ISSUE THREAD

**Issue by kjrstory** [nextfoam/baram-pages#3]
https://github.com/nextfoam/nextfoam-cfd 의 README.md 에서
`export WM_LABEL_SIZE=64 `
64 bit label을  지정하고 있습니다.

단 https://baramcfd.org/installation/2024/04/15/installationSourceCode-post/ 문서를 보면
```bash
  export BARAM_DIR="/opt/baram"
    
  sudo mkdir -p $BARAM_DIR/solvers/openfoam
  sudo cp -a $WM_PROJECT_DIR/platforms/linux64GccDPInt32Opt/bin $BARAM_DIR/solvers/openfoam/
  sudo cp -a $WM_PROJECT_DIR/platforms/linux64GccDPInt32Opt/lib $BARAM_DIR/solvers/openfoam/
  sudo cp -a $WM_PROJECT_DIR/etc $BARAM_DIR/solvers/openfoam/

  sudo mkdir -p $BARAM_DIR/solvers/openfoam/tlib

  sudo cp -a $WM_THIRD_PARTY_DIR/platforms/linux64GccDPInt32/lib/libscotch* $BARAM_DIR/solvers/openfoam/tlib/
  sudo cp -a $WM_THIRD_PARTY_DIR/platforms/linux64GccDPInt32/lib/sys-openmpi/libptscotch* $BARAM_DIR/solvers/openfoam/tlib/
  sudo cp -a $WM_THIRD_PARTY_DIR/platforms/linux64Gcc/fftw-3.3.10/lib/libfftw3* $BARAM_DIR/solvers/openfoam/tlib/
```
여기서는 `linux64GccDPInt32`로 32 bit label의 경로를 지정하고 있습니다.
가이드대로 하면 `linux64GccDPInt64` 폴더만 생성이 되어있습니다.
가이드가 `linux64GccDPInt64`로 바뀌어야 하는 것이 맞을 것 같은데 64 bit label이 nextFoam solver의 필수 사항인지 확실하지 않아 이슈로 남깁니다.

**Comment by kdg5424** [comment]
안녕하세요 넥스트폼입니다.

파악 결과, NextFOAM 솔버 빌드 매뉴얼에 LABEL 설정이 잘못 들어간 것으로 보입니다.
현재 NextFOAM 및 BARAM 모두 LABEL 32bit을 사용합니다.
해당 매뉴얼 내용은 신속히 수정하겠습니다.

감사합니다.

**Comment by kjrstory** [comment]
변경을 확인하여 이슈를 닫겠습니다 :smiley:
